### ISSUE TITLE
Upper incomplete gamma function

### ISSUE THREAD

**Issue by nilgoyette** [stainless-steel/special#5]
Hi Ivan. I'm porting a denoising program from Python to Rust. I realized that I need the "normalised **upper** incomplete gamma function" (what boost calls `gamma_q`). I'm not particularly good in math but I tried to modify your function. I thought it was as simple as changing 2 bounds... it seems I'm wrong! Do you know what would be required to code it?

Or, instead of holding my hand, maybe you had plans to add it yourself since the lower function is already in your lib?

**Comment by IvanUkhov** [comment]
Thanks for the issue! I suppose one should be able to express the upper function in terms of the lower one, in which case the function that is already provided by the crate can be reused. Or do you mean that you’d like to implement a function that computes the upper one directly (for instance, in order to avoid some round-off errors and such)?

**Comment by IvanUkhov** [comment]
The regularized upper incomplete function can then be computed as `1.0 - x.inc_gamma(p)`.

**Comment by nilgoyette** [comment]
Haha, ok, wow, I just made a fool out of myself :) Let just hope that this issue helps other fools. Thank you Ivan!
